# Generated by Django 5.0.4 on 2024-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daycare_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirmPass", models.CharField(max_length=100)),
            ],
        ),
    ]
